### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by srghma** [reflex-frp/reflex-native#4]
1. Will reflex support android? 
The repo wasn't updated for 3 years

Or it's already supported in https://github.com/reflex-frp/reflex-platform ?

2. Is there example of app that compiles to android and iOS?

3. I see several options of compiling https://wiki.haskell.org/Android ? What implementation will be/is selected?
- what compiler it will use? Ghc? Ajhc?
- how bindings to android ndk will be made?

**Comment by alexfmpe** [comment]
I dunno about NDK binding but cross-compiling is simple - see 
  - https://github.com/reflex-frp/reflex-platform/blob/develop/docs/project-development.rst#building-mobile-apps  
  - https://github.com/obsidiansystems/obelisk/#android

**Comment by srghma** [comment]
Sorry for stupid questions:
1. Is THIS repo deprecated?
2. How android support is implemented? Is it rendering html into webview? Or native widgets?

**Comment by alexfmpe** [comment]
1. Dunno, I just stumbled into it at some point. I don't speak for the maintainers or anything
2. Those repos (obelisk exists on top of reflex-platform) do render html into a webview, but unlike ghcjs builds, the actual code is natively compiled, and the browser is only used for rendering. This repo looks like it actually uses native widgets.

**Comment by Dridus** [comment]
1. not deprecated as such, but lacking attention and certainly not production ready. there's a design corner blocking in how to formulate layout in a nice way, I have some branches in my fork which are trying to get there but I haven't had time to focus hard and push through it.
2. this repo is to use the native widgets without any DOM layout engine in between. reflex-dom supports android (and iOS, and traditional web). for android and iOS there's some native shim which provides a DOM renderer (WKWebView on iOS, not sure on android) and then a native binary communicates with that DOM renderer through JSaddle

to answer your original question though this repo is intended to support android at some point, but at this point it's more of an exploration of the concept rather than something to use. if you have a bunch of spare time and want to push it along though we can chat about that :-)

I believe the reflex-platform can generate an iOS and Android app for todomvc, the canonical reflex test app.

closing this issue for now, feel free to reopen it if you think it's necessary.

**Comment by srghma** [comment]
> if you have a bunch of spare time and want to push it along though we can chat about that

let's chat here, so that everyone could see the discussion

what do You have in mind? how do You see that native support for both android and ios?

e.g. would be better to make a 
1. flutter clone - i.e. render widgets (e.g. text) to canvas
2. OR use native widgets (probably bad idea, [this reddit comment](https://www.reddit.com/r/haskell/comments/opsub1/comment/h67xdbd/?utm_source=share&utm_medium=web2x&context=3) writes

> IMO what's missing in haskell right now is a data type for proper text display support. I keep thinking I'll do this, but never have the time. It needs to support things like unicode bidi algorithm, rich text annotations, run generation, line placement and wrapping, word segmentation (at least for western languages), etc. And it needs to do this fast, and be able to provide fast updates (for a text editing component).

**Comment by Dridus** [comment]
In general, my thought to the approach is to provide the common denominator support out of the core reflex-native, and use the platform native widgets. If an app wants to use platform-specific things, the code can be written that way and compose things that are platform-inspecific.

There's a ton of smarts and particular behaviors implemented in the native platforms, so implementing cross-platform support for all of that seems like an (even bigger) rock to move, and the resulting apps would act different to ones implemented using the native platform components.
